# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ffrelayctl < Formula
  desc "A CLI for Firefox Relay"
  homepage "https://github.com/hastefuI/ffrelayctl"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.7.0/ffrelayctl_0.7.0_macos_x86_64.tar.gz"
      sha256 "ad770b5a4c4a46ad320db2a1ac7b550cef55807ab4781f6688d3c19b8ee12a1a"

      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.7.0/ffrelayctl_0.7.0_macos_arm64.tar.gz"
      sha256 "be3c6ba84d8b00aff882b1dcc18cb65bd03ce57ec3b848cdb642997749105364"

      def install
        bin.install "ffrelayctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.7.0/ffrelayctl_0.7.0_linux_x86_64.tar.gz"
      sha256 "81f308c194deca7b6b02cecd3ba7cc3e0b81976ef0efe6086a0933f99567edb8"
      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.7.0/ffrelayctl_0.7.0_linux_arm64.tar.gz"
      sha256 "a7ed662dc1d8331d68876481171b9f878971fba0437f9eabf9a8a0b69b44fc2b"
      def install
        bin.install "ffrelayctl"
      end
    end
  end

  test do
    system "#{bin}/ffrelayctl", "--version"
  end
end
