# This file was generated by GoReleaser. DO NOT EDIT.
cask "diceware" do
  version "1.0.0"

  on_macos do
    on_arm do
      sha256 "c9db71664305f18c6f41cda8119969e1ce0771c74d1ce363150bf5cc46a2c94b"
      url "https://github.com/hastefuI/diceware/releases/download/v#{version}/diceware_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "51839402801dae8942b03858f6444ef49cf32ac65af4a3e7f79725b16c9ba4f7"
      url "https://github.com/hastefuI/diceware/releases/download/v#{version}/diceware_#{version}_macos_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1c83d9b1f6b71ab41514c8acf4d0059b064fc84f1a978653dc59bcea3e542ca5"
      url "https://github.com/hastefuI/diceware/releases/download/v#{version}/diceware_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "afe2bc3700e6b4da03c3ee41c5ea35d9a1667fc276bebda3b425822dc8de58e1"
      url "https://github.com/hastefuI/diceware/releases/download/v#{version}/diceware_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "diceware"
  desc "Diceware passphrase generator with a live terminal view"
  homepage "https://github.com/hastefuI/diceware"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "diceware"

  # No zap stanza required
end
