# This file was generated by GoReleaser. DO NOT EDIT.
cask "ffrelayctl" do
  version "1.1.0"

  on_macos do
    on_arm do
      sha256 "e21992f74282b0d0cda4cf4e843411d341982e8626b391a975d07f752034b0c0"
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v#{version}/ffrelayctl_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "03af9d3adbbe97cad5ac512089c3e0f9761a105a282ae672592252e4e7c0b8ac"
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v#{version}/ffrelayctl_#{version}_macos_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f1237b0bbc4ac6866fe9c9da86b803024e71c5249344ce1d7e8735fdbc88c565"
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v#{version}/ffrelayctl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "35ecdc76e2d111b300f920f46a4338f7566883696cfd2e844b1fb995e2ac7195"
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v#{version}/ffrelayctl_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "ffrelayctl"
  desc "A CLI for Firefox Relay"
  homepage "https://github.com/hastefuI/ffrelayctl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ffrelayctl"

  # No zap stanza required
end
