# This file was generated by GoReleaser. DO NOT EDIT.
cask "recall" do
  version "0.8.0"

  on_macos do
    on_arm do
      sha256 "e045b6d5a1fdfe2a5923ec22212e2f1870062e790ada4b9cbbc0c5d83db7a16f"
      url "https://github.com/hastefuI/recall/releases/download/v#{version}/recall_#{version}_macos_arm64.tar.gz"
    end
    on_intel do
      sha256 "c99cc94f8431a63add82fe8b2afb2075ce4720325f7d7b87d5ef295a31445e51"
      url "https://github.com/hastefuI/recall/releases/download/v#{version}/recall_#{version}_macos_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9253522dec7b3aa27a42a50ad4654962faba967abfa21a179665375de8d15a2e"
      url "https://github.com/hastefuI/recall/releases/download/v#{version}/recall_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "19de6f6efe335945f212195a3ae57057a3abd9564612d1b02ae9239b6e93b2f8"
      url "https://github.com/hastefuI/recall/releases/download/v#{version}/recall_#{version}_linux_x86_64.tar.gz"
    end
  end

  name "recall"
  desc "Cache and recall CLI command results with a TTL"
  homepage "https://github.com/hastefuI/recall"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "recall"

  # No zap stanza required
end
