# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ffrelayctl < Formula
  desc "A CLI for Firefox Relay"
  homepage "https://github.com/hastefuI/ffrelayctl"
  version "0.8.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.8.0/ffrelayctl_0.8.0_macos_x86_64.tar.gz"
      sha256 "619d5aae581532fbcda17ec08ee694671b67aa1ce1ddbc6086e07a6b8bd21299"

      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.8.0/ffrelayctl_0.8.0_macos_arm64.tar.gz"
      sha256 "8e303fbc0a7266c8563a498c182c507f35cb6d2c8a28cece68e6567d1df81327"

      def install
        bin.install "ffrelayctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.8.0/ffrelayctl_0.8.0_linux_x86_64.tar.gz"
      sha256 "0dbfc6d6408081666149d76f694efd74cad144902ce042344733a273e6b10201"
      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.8.0/ffrelayctl_0.8.0_linux_arm64.tar.gz"
      sha256 "99f4acbc52dacb5b0bb25e80534275980ea818aebee6a89aef57792fab7db15d"
      def install
        bin.install "ffrelayctl"
      end
    end
  end

  test do
    system "#{bin}/ffrelayctl", "--version"
  end
end
