# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ffrelayctl < Formula
  desc "A CLI for Firefox Relay"
  homepage "https://github.com/hastefuI/ffrelayctl"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v1.0.0/ffrelayctl_1.0.0_macos_x86_64.tar.gz"
      sha256 "d6cee1f3a1e429a500075fcc36ae272971b439e6a03a5bc83e898e3270a08d7a"

      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v1.0.0/ffrelayctl_1.0.0_macos_arm64.tar.gz"
      sha256 "8cb57cedc7ed6b230c9c629f80ea721213db630090196be2033e95c597090dcb"

      def install
        bin.install "ffrelayctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v1.0.0/ffrelayctl_1.0.0_linux_x86_64.tar.gz"
      sha256 "326c7656d2aac69176dd225c3c577771509372191fcae4ff681c26c62fc403be"
      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v1.0.0/ffrelayctl_1.0.0_linux_arm64.tar.gz"
      sha256 "c3582953fef977fecd1054c36bc2673cbe1a72f15dd9a5b8d0705c7ebbb6e18c"
      def install
        bin.install "ffrelayctl"
      end
    end
  end

  test do
    system "#{bin}/ffrelayctl", "--version"
  end
end
