# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ffrelayctl < Formula
  desc "A CLI for Firefox Relay"
  homepage "https://github.com/hastefuI/ffrelayctl"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.9.0/ffrelayctl_0.9.0_macos_x86_64.tar.gz"
      sha256 "b1d4bcb7284cfc8ef05398ff3359d1016aa689a21940923dd8cc3b152553375b"

      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.9.0/ffrelayctl_0.9.0_macos_arm64.tar.gz"
      sha256 "87bcd896922b80dd3c7b2894a3a9f8b83505b239e5cfae0641756c842502bf8a"

      def install
        bin.install "ffrelayctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.9.0/ffrelayctl_0.9.0_linux_x86_64.tar.gz"
      sha256 "77dec613f37a1f6923cda74d3cbd1c3d83ffa197c2891fbe1cbe46060ca17789"
      def install
        bin.install "ffrelayctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hastefuI/ffrelayctl/releases/download/v0.9.0/ffrelayctl_0.9.0_linux_arm64.tar.gz"
      sha256 "91a7e7071dbb368fdf73b4d5bf2a8e436d64efacd40bcefacf730b293794fc9b"
      def install
        bin.install "ffrelayctl"
      end
    end
  end

  test do
    system "#{bin}/ffrelayctl", "--version"
  end
end
